### ISSUE TITLE
csv file always error

### ISSUE THREAD

**Issue by noviriasyifaunnafsi** [nafsi20/rice-farming-with-crop-rotation#5]
i'm not sure how to fix this error that says:

> It looks like row 2 should actually have 1 column, instead of 3. in line 1.

look at this file: https://github.com/nafsi20/rice-farming-with-crop-rotation/blob/main/new_variable_estimates.csv

@nafsi20 @Kongtonkun @inkyin3796 @lian24

**Comment by Kongtonkun** [comment]
Do you want to create on R?

**Comment by Kongtonkun** [comment]
Hi I didn’t found this. We don’t have new input variable cost.csv in R.
This is why we connot run in the program.

**Comment by noviriasyifaunnafsi** [comment]
there was a file, but i have updated with the new one
this is actually have solved. i have closed this issue.
maybe i should delete it anyway haha..

please check on another issue that i just raised
